return {}
-- return {
--   {
--     "zbirenbaum/copilot.lua",
--     cmd = "Copilot",
--     build = ":Copilot auth",
--     event = "InsertEnter",
--     opts = {
--       suggestion = {
--         enabled = false,
--         auto_trigger = false,
--         keymap = {
--           accept = "<Tab>",
--           close = "<Esc>",
--           next = "<C-J>",
--           prev = "<C-K>",
--           select = "<CR>",
--           dismiss = "<C-X>",
--         },
--       },
--       panel = {
--         enabled = false,
--       },
--     },
--   },
--   {
--     "zbirenbaum/copilot-cmp",
--     dependencies = {
--       "hrsh7th/nvim-cmp",
--       "zbirenbaum/copilot.lua",
--     },
--     config = true,
--   },
-- }
